/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type WeeklyActivity = {
  _id: string;
  _type: "weeklyActivity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtitle?: string;
  schedule: string;
  body: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  displayOrder: number;
  cards?: Array<{
    title: string;
    body: string;
    linkUrl?: string;
    linkText?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "activityCard";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type WardEvent = {
  _id: string;
  _type: "wardEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status: "pending" | "approved" | "rejected";
  title: string;
  dateTime: string;
  description?: string;
  location?: string;
  submitterName?: string;
  submitterEmail?: string;
};

export type SacramentProgram = {
  _id: string;
  _type: "sacramentProgram";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  meetingDate: string;
  presiding?: string;
  conducting?: string;
  chorister?: string;
  organist?: string;
  program?: Array<
    | {
        label?: string;
        number?: string;
        title: string;
        _type: "programHymn";
        _key: string;
      }
    | {
        type: "Opening Prayer" | "Closing Prayer";
        person: string;
        _type: "programPrayer";
        _key: string;
      }
    | {
        name: string;
        topic?: string;
        _type: "programSpeaker";
        _key: string;
      }
    | {
        title: string;
        performer?: string;
        _type: "programMusicalNumber";
        _key: string;
      }
  >;
};

export type LeaderCard = {
  _id: string;
  _type: "leaderCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  title: string;
  phone?: string;
  email?: string;
  displayOrder: number;
};

export type HomeSectionBottom = {
  _id: string;
  _type: "homeSectionBottom";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eyebrow?: string;
  heading?: string;
  body?: string;
};

export type HomeSectionTop = {
  _id: string;
  _type: "homeSectionTop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eyebrow?: string;
  heading?: string;
  body?: string;
};

export type HeroImage = {
  _id: string;
  _type: "heroImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | WeeklyActivity
  | SanityImageCrop
  | SanityImageHotspot
  | WardEvent
  | SacramentProgram
  | LeaderCard
  | HomeSectionBottom
  | HomeSectionTop
  | HeroImage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: lib/sanity/queries.ts
// Variable: heroImageQuery
// Query: *[_type == "heroImage"][0]{    _id,    title,    image {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }  }
export type HeroImageQueryResult = {
  _id: string;
  title: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
} | null;

// Source: lib/sanity/queries.ts
// Variable: homeSectionTopQuery
// Query: *[_type == "homeSectionTop"][0]{    _id,    eyebrow,    heading,    body,    desktopImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot },    mobileImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }  }
export type HomeSectionTopQueryResult = {
  _id: string;
  eyebrow: string | null;
  heading: string | null;
  body: string | null;
  desktopImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  mobileImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
} | null;

// Source: lib/sanity/queries.ts
// Variable: homeSectionBottomQuery
// Query: *[_type == "homeSectionBottom"][0]{    _id,    eyebrow,    heading,    body,    desktopImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot },    mobileImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }  }
export type HomeSectionBottomQueryResult = {
  _id: string;
  eyebrow: string | null;
  heading: string | null;
  body: string | null;
  desktopImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  mobileImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
} | null;

// Source: lib/sanity/queries.ts
// Variable: leaderCardsQuery
// Query: *[_type == "leaderCard"] | order(displayOrder asc){    _id,    name,    title,    phone,    email,    displayOrder  }
export type LeaderCardsQueryResult = Array<{
  _id: string;
  name: string;
  title: string;
  phone: string | null;
  email: string | null;
  displayOrder: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: weeklyActivitiesQuery
// Query: *[_type == "weeklyActivity"] | order(displayOrder asc){    _id,    title,    subtitle,    schedule,    body,    displayOrder,    image {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot },    cards[]{      _key,      title,      body,      linkUrl,      linkText,      image {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }    }  }
export type WeeklyActivitiesQueryResult = Array<{
  _id: string;
  title: string;
  subtitle: string | null;
  schedule: string;
  body: string;
  displayOrder: number;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  cards: Array<{
    _key: string;
    title: string;
    body: string;
    linkUrl: string | null;
    linkText: string | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }> | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: sacramentProgramQuery
// Query: *[_type == "sacramentProgram"] | order(meetingDate desc)[0]{    _id,    meetingDate,    presiding,    conducting,    chorister,    organist,    program[]{      _key,      _type,      label,      number,      title,      type,      person,      name,      topic,      performer    }  }
export type SacramentProgramQueryResult = {
  _id: string;
  meetingDate: string;
  presiding: string | null;
  conducting: string | null;
  chorister: string | null;
  organist: string | null;
  program: Array<
    | {
        _key: string;
        _type: "programHymn";
        label: string | null;
        number: string | null;
        title: string;
        type: null;
        person: null;
        name: null;
        topic: null;
        performer: null;
      }
    | {
        _key: string;
        _type: "programMusicalNumber";
        label: null;
        number: null;
        title: string;
        type: null;
        person: null;
        name: null;
        topic: null;
        performer: string | null;
      }
    | {
        _key: string;
        _type: "programPrayer";
        label: null;
        number: null;
        title: null;
        type: "Closing Prayer" | "Opening Prayer";
        person: string;
        name: null;
        topic: null;
        performer: null;
      }
    | {
        _key: string;
        _type: "programSpeaker";
        label: null;
        number: null;
        title: null;
        type: null;
        person: null;
        name: string;
        topic: string | null;
        performer: null;
      }
  > | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: upcomingEventsQuery
// Query: *[_type == "wardEvent" && status == "approved" && dateTime >= $cutoff] | order(dateTime asc)[0...20]{    _id,    title,    dateTime,    description,    location  }
export type UpcomingEventsQueryResult = Array<{
  _id: string;
  title: string;
  dateTime: string;
  description: string | null;
  location: string | null;
}>;
