/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type WardEvent = {
  _id: string;
  _type: "wardEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  dateTime: string;
  description?: string;
  location?: string;
};

export type LeaderCard = {
  _id: string;
  _type: "leaderCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  title: string;
  phone?: string;
  email?: string;
  displayOrder: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomeSectionBottom = {
  _id: string;
  _type: "homeSectionBottom";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eyebrow?: string;
  heading?: string;
  body?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type HomeSectionTop = {
  _id: string;
  _type: "homeSectionTop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eyebrow?: string;
  heading?: string;
  body?: string;
};

export type HeroImage = {
  _id: string;
  _type: "heroImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | WardEvent
  | LeaderCard
  | SanityImageAssetReference
  | HomeSectionBottom
  | SanityImageCrop
  | SanityImageHotspot
  | HomeSectionTop
  | HeroImage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: lib/sanity/queries.ts
// Variable: heroImageQuery
// Query: *[_type == "heroImage"][0]{    _id,    title,    image {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }  }
export type HeroImageQueryResult = {
  _id: string;
  title: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
} | null;

// Source: lib/sanity/queries.ts
// Variable: homeSectionTopQuery
// Query: *[_type == "homeSectionTop"][0]{    _id,    eyebrow,    heading,    body,    desktopImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot },    mobileImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }  }
export type HomeSectionTopQueryResult = {
  _id: string;
  eyebrow: string | null;
  heading: string | null;
  body: string | null;
  desktopImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  mobileImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
} | null;

// Source: lib/sanity/queries.ts
// Variable: homeSectionBottomQuery
// Query: *[_type == "homeSectionBottom"][0]{    _id,    eyebrow,    heading,    body,    desktopImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot },    mobileImage {   asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height }    }  },  crop,  hotspot }  }
export type HomeSectionBottomQueryResult = {
  _id: string;
  eyebrow: string | null;
  heading: string | null;
  body: string | null;
  desktopImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
  mobileImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
} | null;

// Source: lib/sanity/queries.ts
// Variable: leaderCardsQuery
// Query: *[_type == "leaderCard"] | order(displayOrder asc){    _id,    name,    title,    phone,    email,    displayOrder  }
export type LeaderCardsQueryResult = Array<{
  _id: string;
  name: string;
  title: string;
  phone: string | null;
  email: string | null;
  displayOrder: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: upcomingEventsQuery
// Query: *[_type == "wardEvent" && dateTime >= now()] | order(dateTime asc)[0...20]{    _id,    title,    dateTime,    description,    location  }
export type UpcomingEventsQueryResult = Array<{
  _id: string;
  title: string;
  dateTime: string;
  description: string | null;
  location: string | null;
}>;
